# Generated by Django 3.2.18 on 2023-03-30 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_courses_courseteachers_lesson"),
    ]

    operations = []
